title: AdminLTE v3.2 Documentation
version: v3.2
description: AdminLTE v3.2 Documentation

baseurl: /docs/3.2
url: https://adminlte.io

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

navigation:
  - title: Installation
    url: index.md
    icon: fas fa-microchip
  - title: Dependencies & Plugins
    url: dependencies.md
    icon: fas fa-handshake
  - title: Layout
    url: layout.md
    icon: fas fa-copy
  - title: Components
    icon: fas fa-th
    url: components
    subitems:
      - title: Main Header
        url: components/main-header.md
      - title: Main Sidebar
        url: components/main-sidebar.md
      - title: Control Sidebar
        url: components/control-sidebar.md
      - title: Card
        url: components/cards.md
      - title: Small-/ Info-Box
        url: components/boxes.md
      - title: Direct Chat
        url: components/direct-chat.md
      - title: Timeline
        url: components/timeline.md
      - title: Ribbons
        url: components/ribbons.md
      - title: Miscellaneous
        url: components/miscellaneous.md
      - title: Plugins
        url: components/plugins.md
  - title: JavaScript
    icon: fas fa-code
    url: javascript
    subitems:
      - title: Layout
        url: javascript/layout.md
      - title: Push Menu
        url: javascript/push-menu.md
      - title: Treeview
        url: javascript/treeview.md
      - title: Card Widget
        url: javascript/card-widget.md
      - title: CardRefresh
        url: javascript/card-refresh.md
      - title: Control Sidebar
        url: javascript/control-sidebar.md
      - title: Direct Chat
        url: javascript/direct-chat.md
      - title: Todo List
        url: javascript/todo-list.md
      - title: Toasts
        url: javascript/toasts.md
      - title: Sidebar Search
        url: javascript/sidebar-search.md
      - title: Expandable Tables
        url: javascript/expandable-tables.md
      - title: IFrame
        url: javascript/iframe.md
      - title: Navbar Search
        url: javascript/navbar-search.md
  - title: Browser Support
    url: browser-support.md
    icon: fab fa-chrome
  - title: Implementations
    url: implementations.md
    icon: fas fa-bookmark
  - title: Additional Styles
    url: additional-styles.md
    icon: fas fa-mortar-pestle
  - title: Upgrade Guide
    url: upgrade-guide.md
    icon: fas fa-hand-point-up
  - title: Contributing Guide
    url: how-to-contribute.md
    icon: fas fa-hands-helping
  - title: FAQ
    url: faq.md
    icon: fas fa-question-circle
  - title: License
    url: license.md
    icon: fas fa-file-contract
